# Generated by Django 5.1.3 on 2026-01-10 00:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'especies',
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aws_s3_file', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'historiales_medicos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('TUTOR', 'Tutor'), ('ADOPTANTE', 'Adoptante'), ('ADMIN', 'Administrador')], max_length=15)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('foto_perfil_s3', models.CharField(default='', max_length=2048)),
                ('foto_perfil_file', models.ImageField(blank=True, null=True, upload_to='tmp_perfiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1)),
                ('edad_meses', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=15)),
                ('fecha_registro', models.DateField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('tamano_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(db_column='especie_id', on_delete=django.db.models.deletion.RESTRICT, related_name='mascotas', to='catalog.especie')),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
        migrations.CreateModel(
            name='FotoMascota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tmp_fotos_mascotas/')),
                ('s3_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('fecha', models.DateField()),
                ('mascota', models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='catalog.mascota')),
            ],
            options={
                'db_table': 'fotos_mascota',
            },
        ),
        migrations.CreateModel(
            name='CartillaMedica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('enfermedades_anteriores', models.TextField(blank=True, null=True)),
                ('actitud', models.CharField(blank=True, choices=[('ASTENICO', 'Asténico'), ('APOPLETICO', 'Apoplético'), ('LINFATICO', 'Linfático')], max_length=50, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('condicion_corporal', models.CharField(blank=True, choices=[('OBESO', 'Obeso'), ('NORMAL', 'Normal'), ('DELGADO', 'Delgado'), ('CAQUECTICO', 'Caquéctico')], max_length=50, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado_deshidratacion', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('5', 'Al 5%'), ('6-7', 'Al 6-7%'), ('8-9', 'Al 8-9%'), ('10+', 'Más de 10%')], max_length=50, null=True)),
                ('mucosa_oral_conjuntival', models.CharField(blank=True, max_length=50, null=True)),
                ('mucosa_intima', models.CharField(blank=True, max_length=50, null=True)),
                ('mucosa_rectal', models.CharField(blank=True, max_length=50, null=True)),
                ('mucosa_ojos', models.CharField(blank=True, max_length=50, null=True)),
                ('mucosa_nodulos', models.CharField(blank=True, max_length=50, null=True)),
                ('mucosa_piel', models.CharField(blank=True, max_length=50, null=True)),
                ('locomocion', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frec_cardiaca_lpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frec_respiratoria_rpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('historial_medico', models.ForeignKey(blank=True, db_column='historial_medico_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartillas', to='catalog.historialmedico')),
                ('mascota', models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.CASCADE, related_name='cartillas', to='catalog.mascota')),
            ],
            options={
                'db_table': 'cartillas_medicas',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=25)),
                ('tiene_patio', models.BooleanField(default=False)),
                ('ocupacion', models.CharField(blank=True, max_length=120, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('foto_ci_s3', models.CharField(default='', max_length=2048)),
                ('ci_file', models.FileField(blank=True, null=True, upload_to='tmp_adoptantes/ci/')),
                ('foto_garante_s3', models.CharField(default='', max_length=2048)),
                ('garante_file', models.FileField(blank=True, null=True, upload_to='tmp_adoptantes/garante/')),
                ('foto_recibo_luz_s3', models.CharField(default='', max_length=2048)),
                ('recibo_luz_file', models.FileField(blank=True, null=True, upload_to='tmp_adoptantes/recibo_luz/')),
                ('foto_fachada_s3', models.CharField(default='', max_length=2048)),
                ('fachada_file', models.FileField(blank=True, null=True, upload_to='tmp_adoptantes/fachada/')),
                ('foto_domicilio_s3', models.CharField(default='', max_length=2048)),
                ('domicilio_file', models.FileField(blank=True, null=True, upload_to='tmp_adoptantes/domicilio/')),
                ('foto_croquis_s3', models.CharField(default='', max_length=2048)),
                ('croquis_file', models.FileField(blank=True, null=True, upload_to='tmp_adoptantes/croquis/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_adoptante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles_adoptante',
            },
        ),
        migrations.CreateModel(
            name='PerfilTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles_tutor',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='perfil_tutor',
            field=models.ForeignKey(db_column='perfil_tutor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='mascotas', to='catalog.perfiltutor'),
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('especie', models.ForeignKey(db_column='especie_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.especie')),
            ],
            options={
                'db_table': 'razas',
                'unique_together': {('especie', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(blank=True, db_column='raza_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='catalog.raza'),
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('motivacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudes', to='catalog.mascota')),
                ('perfil_adoptante', models.ForeignKey(db_column='perfil_adoptante_id', on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudes', to='catalog.perfiladoptante')),
            ],
            options={
                'db_table': 'solicitudes_adopcion',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoSolicitud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tmp_seguimientos/')),
                ('s3_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('obs', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(db_column='solicitud_id', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='catalog.solicitudadopcion')),
            ],
            options={
                'db_table': 'seguimientos_solicitud',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('modo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Automático')], default='MANUAL', max_length=10)),
                ('frecuencia', models.CharField(blank=True, choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Cada 3 meses')], max_length=12, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('proximo_envio', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(db_column='solicitud_id', on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_config', to='catalog.solicitudadopcion')),
            ],
            options={
                'db_table': 'seguimientos_config',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=140)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('perfil_tutor', models.ForeignKey(db_column='perfil_tutor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='notificaciones', to='catalog.perfiltutor')),
                ('solicitud', models.ForeignKey(db_column='solicitud_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='catalog.solicitudadopcion')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('producto', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('veterinaria', models.CharField(blank=True, max_length=120, null=True)),
                ('cartilla_medica', models.ForeignKey(db_column='cartilla_medica_id', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='catalog.cartillamedica')),
            ],
            options={
                'db_table': 'vacunas',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, db_column='autor_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='valoraciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='valoraciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'valoraciones',
                'unique_together': {('autor', 'usuario')},
            },
        ),
    ]
