# Generated by Django 5.1.3 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfiltutor',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
