# Generated by Django 5.1.3 on 2026-10-08 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mascota_activo_alter_perfiltutor_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotomascota',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una mascota registrada con este nombre.'}, max_length=100, unique=True),
        ),
    ]
