# Generated by Django 5.1.3 on 2025-10-26 02:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='catalogo.especie')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'especie')},
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1)),
                ('edad', models.PositiveIntegerField(help_text='Edad en meses', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('id_tutor', models.BigIntegerField(blank=True, null=True)),
                ('id_cartilla', models.BigIntegerField(blank=True, null=True)),
                ('id_ubicacion', models.BigIntegerField(blank=True, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='catalogo.especie')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='catalogo.raza')),
            ],
            options={
                'ordering': ['-fecha_registro', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('edad__gte', 0)), name='mascota_edad_gte_0'), models.CheckConstraint(condition=models.Q(('sexo__in', ['M', 'F'])), name='mascota_sexo_mf')],
            },
        ),
    ]
